use std::any::TypeId;
use std::collections::HashMap;

use crate::bundle::Bundle;
use crate::component::{ComponentId, ComponentRegistry};
use crate::storage::archetype::{ArchetypeId, Archetypes};

/// Cached column layout for a Table type. Resolved once on first use.
pub struct TableDescriptor {
    pub archetype_id: ArchetypeId,
    /// Maps field index (0, 1, 2...) to archetype column index.
    /// Field order matches struct declaration order; column order is
    /// sorted by ComponentId (archetype canonical order).
    pub col_indices: Vec<usize>,
    /// Item sizes for each field in field declaration order.
    pub item_sizes: Vec<usize>,
}

/// A named struct that serves as both data container and schema declaration.
/// Generated by `#[derive(Table)]`.
///
/// # Safety
/// Implementors must ensure that `register` returns component IDs matching
/// the actual field types in declaration order, and `FIELD_COUNT` matches
/// the actual number of fields.
pub unsafe trait Table: Bundle + Sized {
    const FIELD_COUNT: usize;

    /// The immutable row reference type (e.g. `TransformRef<'w>`).
    type Ref<'w>: TableRow<'w>;
    /// The mutable row reference type (e.g. `TransformMut<'w>`).
    type Mut<'w>: TableRow<'w>;

    /// Register all field components. Returns ComponentIds in field declaration order.
    fn register(registry: &mut ComponentRegistry) -> Vec<ComponentId>;
}

/// Trait for constructing typed row references from raw column pointers.
///
/// # Safety
/// Implementors must ensure the pointers and row offset produce valid references.
/// Generated by `#[derive(Table)]` for `FooRef<'w>` and `FooMut<'w>`.
pub unsafe trait TableRow<'w>: Sized {
    /// Construct a row reference from raw column pointers and a row offset.
    /// `col_ptrs` contains one `(*mut u8, item_size)` per field in field order.
    ///
    /// # Safety
    /// `row` must be in bounds. Pointers must be valid for the row offset.
    unsafe fn from_row(col_ptrs: &[(*mut u8, usize)], row: usize) -> Self;
}

/// Cache of resolved TableDescriptors, keyed by TypeId.
pub(crate) struct TableCache {
    descriptors: HashMap<TypeId, TableDescriptor>,
}

impl TableCache {
    pub fn new() -> Self {
        Self {
            descriptors: HashMap::new(),
        }
    }

    /// Get or create the descriptor for a Table type.
    pub fn get_or_create<T: Table>(
        &mut self,
        components: &mut ComponentRegistry,
        archetypes: &mut Archetypes,
    ) -> &TableDescriptor {
        let type_id = TypeId::of::<T>();
        self.descriptors.entry(type_id).or_insert_with(|| {
            // Register components in field order
            let field_ids = T::register(components);

            // Archetype uses sorted component IDs
            let mut sorted_ids = field_ids.clone();
            sorted_ids.sort_unstable();
            sorted_ids.dedup();
            assert_eq!(
                sorted_ids.len(),
                T::FIELD_COUNT,
                "duplicate component types in table"
            );

            let arch_id = archetypes.get_or_create(&sorted_ids, components);
            let archetype = &archetypes.archetypes[arch_id.0];

            // Map field index -> archetype column index
            let col_indices: Vec<usize> = field_ids
                .iter()
                .map(|comp_id| {
                    archetype
                        .column_index(*comp_id)
                        .expect("component not in archetype")
                })
                .collect();

            let item_sizes: Vec<usize> = field_ids
                .iter()
                .map(|&comp_id| components.info(comp_id).layout.size())
                .collect();

            TableDescriptor {
                archetype_id: arch_id,
                col_indices,
                item_sizes,
            }
        })
    }
}

/// Iterator over rows of a table's archetype, yielding raw column pointers per field.
pub struct TableIter<'w> {
    /// One entry per field: (column_start_ptr, item_size).
    col_ptrs: Vec<(*mut u8, usize)>,
    len: usize,
    current_row: usize,
    _marker: std::marker::PhantomData<&'w ()>,
}

// Safety: column pointers come from BlobVec which stores Send+Sync component data.
unsafe impl Send for TableIter<'_> {}
unsafe impl Sync for TableIter<'_> {}

impl<'w> TableIter<'w> {
    pub(crate) fn new(col_ptrs: Vec<(*mut u8, usize)>, len: usize) -> Self {
        Self {
            col_ptrs,
            len,
            current_row: 0,
            _marker: std::marker::PhantomData,
        }
    }
}

impl<'w> Iterator for TableIter<'w> {
    /// Yields a Vec of raw pointers, one per field in field order, pointing to the current row.
    type Item = Vec<*mut u8>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.current_row >= self.len {
            return None;
        }
        let row = self.current_row;
        self.current_row += 1;
        Some(
            self.col_ptrs
                .iter()
                .map(|&(ptr, item_size)| unsafe { ptr.add(row * item_size) })
                .collect(),
        )
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let remaining = self.len - self.current_row;
        (remaining, Some(remaining))
    }
}

/// Typed iterator over rows of a table, yielding `R: TableRow` per row.
pub struct TableTypedIter<'w, R: TableRow<'w>> {
    col_ptrs: Vec<(*mut u8, usize)>,
    len: usize,
    current_row: usize,
    _marker: std::marker::PhantomData<&'w R>,
}

// Safety: column pointers come from BlobVec which stores Send+Sync component data.
unsafe impl<'w, R: TableRow<'w>> Send for TableTypedIter<'w, R> {}
unsafe impl<'w, R: TableRow<'w>> Sync for TableTypedIter<'w, R> {}

impl<'w, R: TableRow<'w>> TableTypedIter<'w, R> {
    pub(crate) fn new(col_ptrs: Vec<(*mut u8, usize)>, len: usize) -> Self {
        Self {
            col_ptrs,
            len,
            current_row: 0,
            _marker: std::marker::PhantomData,
        }
    }
}

impl<'w, R: TableRow<'w>> Iterator for TableTypedIter<'w, R> {
    type Item = R;

    fn next(&mut self) -> Option<R> {
        if self.current_row >= self.len {
            return None;
        }
        let row = self.current_row;
        self.current_row += 1;
        Some(unsafe { R::from_row(&self.col_ptrs, row) })
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let remaining = self.len - self.current_row;
        (remaining, Some(remaining))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::ComponentRegistry;
    use crate::storage::archetype::Archetypes;

    // Manual Table impl for testing (before derive macro works)
    #[derive(Clone, Copy, Debug, PartialEq)]
    struct Pos {
        x: f32,
        y: f32,
    }
    #[derive(Clone, Copy, Debug, PartialEq)]
    struct Vel {
        dx: f32,
        dy: f32,
    }

    struct PosVel {
        pos: Pos,
        vel: Vel,
    }

    unsafe impl Bundle for PosVel {
        fn component_ids(registry: &mut ComponentRegistry) -> Vec<ComponentId> {
            let mut ids = vec![registry.register::<Pos>(), registry.register::<Vel>()];
            ids.sort_unstable();
            ids.dedup();
            assert_eq!(ids.len(), 2);
            ids
        }

        unsafe fn put(
            self,
            registry: &ComponentRegistry,
            func: &mut dyn FnMut(ComponentId, *const u8, std::alloc::Layout),
        ) {
            let pos = std::mem::ManuallyDrop::new(self.pos);
            func(
                registry.id::<Pos>().unwrap(),
                &*pos as *const Pos as *const u8,
                std::alloc::Layout::new::<Pos>(),
            );
            let vel = std::mem::ManuallyDrop::new(self.vel);
            func(
                registry.id::<Vel>().unwrap(),
                &*vel as *const Vel as *const u8,
                std::alloc::Layout::new::<Vel>(),
            );
        }
    }

    // Manual Ref/Mut types for PosVel (mirroring what derive generates)
    struct PosVelRef<'w> {
        pos: &'w Pos,
        vel: &'w Vel,
    }
    struct PosVelMut<'w> {
        pos: &'w mut Pos,
        #[allow(dead_code)]
        vel: &'w mut Vel,
    }
    unsafe impl<'w> TableRow<'w> for PosVelRef<'w> {
        unsafe fn from_row(col_ptrs: &[(*mut u8, usize)], row: usize) -> Self {
            Self {
                pos: &*(col_ptrs[0].0.add(row * col_ptrs[0].1) as *const Pos),
                vel: &*(col_ptrs[1].0.add(row * col_ptrs[1].1) as *const Vel),
            }
        }
    }
    unsafe impl<'w> TableRow<'w> for PosVelMut<'w> {
        unsafe fn from_row(col_ptrs: &[(*mut u8, usize)], row: usize) -> Self {
            Self {
                pos: &mut *(col_ptrs[0].0.add(row * col_ptrs[0].1) as *mut Pos),
                vel: &mut *(col_ptrs[1].0.add(row * col_ptrs[1].1) as *mut Vel),
            }
        }
    }

    unsafe impl Table for PosVel {
        const FIELD_COUNT: usize = 2;
        type Ref<'w> = PosVelRef<'w>;
        type Mut<'w> = PosVelMut<'w>;

        fn register(registry: &mut ComponentRegistry) -> Vec<ComponentId> {
            vec![registry.register::<Pos>(), registry.register::<Vel>()]
        }
    }

    #[test]
    fn descriptor_resolves_correctly() {
        let mut components = ComponentRegistry::new();
        let mut archetypes = Archetypes::new();
        let mut cache = TableCache::new();

        let desc = cache.get_or_create::<PosVel>(&mut components, &mut archetypes);
        assert_eq!(desc.col_indices.len(), 2);
        assert_eq!(desc.item_sizes.len(), 2);
    }

    #[test]
    fn descriptor_is_cached() {
        let mut components = ComponentRegistry::new();
        let mut archetypes = Archetypes::new();
        let mut cache = TableCache::new();

        let id1 = cache
            .get_or_create::<PosVel>(&mut components, &mut archetypes)
            .archetype_id;
        let id2 = cache
            .get_or_create::<PosVel>(&mut components, &mut archetypes)
            .archetype_id;
        assert_eq!(id1, id2);
    }

    #[test]
    fn query_table_yields_correct_data() {
        let mut world = crate::world::World::new();
        world.spawn(PosVel {
            pos: Pos { x: 1.0, y: 2.0 },
            vel: Vel { dx: 3.0, dy: 4.0 },
        });
        world.spawn(PosVel {
            pos: Pos { x: 5.0, y: 6.0 },
            vel: Vel { dx: 7.0, dy: 8.0 },
        });

        let rows: Vec<(Pos, Vel)> = world
            .query_table_raw::<PosVel>()
            .map(|ptrs| unsafe {
                (
                    std::ptr::read(ptrs[0] as *const Pos),
                    std::ptr::read(ptrs[1] as *const Vel),
                )
            })
            .collect();

        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].0.x, 1.0);
        assert_eq!(rows[0].1.dx, 3.0);
        assert_eq!(rows[1].0.x, 5.0);
    }

    #[test]
    fn query_table_raw_allows_mutation() {
        let mut world = crate::world::World::new();
        let e = world.spawn(PosVel {
            pos: Pos { x: 1.0, y: 2.0 },
            vel: Vel { dx: 3.0, dy: 4.0 },
        });

        for ptrs in world.query_table_raw::<PosVel>() {
            unsafe {
                let pos = &mut *(ptrs[0] as *mut Pos);
                pos.x += 10.0;
            }
        }

        assert_eq!(world.get::<Pos>(e), Some(&Pos { x: 11.0, y: 2.0 }));
    }

    #[test]
    fn query_table_interop_with_dynamic_query() {
        let mut world = crate::world::World::new();
        world.spawn(PosVel {
            pos: Pos { x: 1.0, y: 2.0 },
            vel: Vel { dx: 3.0, dy: 4.0 },
        });

        // Dynamic query finds the same entity
        let count = world.query::<(&Pos, &Vel)>().count();
        assert_eq!(count, 1);

        let pos = world.query::<&Pos>().next().unwrap();
        assert_eq!(pos.x, 1.0);
    }

    #[test]
    fn query_table_empty() {
        let mut world = crate::world::World::new();
        let count = world.query_table_raw::<PosVel>().count();
        assert_eq!(count, 0);
    }

    #[test]
    fn col_indices_map_field_to_column() {
        let mut components = ComponentRegistry::new();
        let mut archetypes = Archetypes::new();
        let mut cache = TableCache::new();

        let desc = cache.get_or_create::<PosVel>(&mut components, &mut archetypes);
        // Both fields should have valid column indices
        let archetype = &archetypes.archetypes[desc.archetype_id.0];
        for &col_idx in &desc.col_indices {
            assert!(col_idx < archetype.columns.len());
        }
    }

    // --- Tests using #[derive(Table)] ---

    #[derive(Clone, Copy, Debug, PartialEq, minkowski_derive::Table)]
    struct Transform {
        pos: Pos,
        vel: Vel,
    }

    #[test]
    fn derive_bundle_spawn() {
        let mut world = crate::world::World::new();
        let e = world.spawn(Transform {
            pos: Pos { x: 1.0, y: 2.0 },
            vel: Vel { dx: 3.0, dy: 4.0 },
        });
        assert_eq!(world.get::<Pos>(e), Some(&Pos { x: 1.0, y: 2.0 }));
        assert_eq!(world.get::<Vel>(e), Some(&Vel { dx: 3.0, dy: 4.0 }));
    }

    #[test]
    fn derive_table_field_count() {
        assert_eq!(<Transform as Table>::FIELD_COUNT, 2);
    }

    #[test]
    fn derive_table_register() {
        let mut reg = ComponentRegistry::new();
        let ids = Transform::register(&mut reg);
        assert_eq!(ids.len(), 2);
    }

    #[test]
    fn derive_interop_dynamic_query() {
        let mut world = crate::world::World::new();
        world.spawn(Transform {
            pos: Pos { x: 5.0, y: 6.0 },
            vel: Vel { dx: 7.0, dy: 8.0 },
        });

        let pos = world.query::<&Pos>().next().unwrap();
        assert_eq!(pos.x, 5.0);
    }

    #[test]
    fn derive_query_table_raw() {
        let mut world = crate::world::World::new();
        world.spawn(Transform {
            pos: Pos { x: 1.0, y: 2.0 },
            vel: Vel { dx: 3.0, dy: 4.0 },
        });
        world.spawn(Transform {
            pos: Pos { x: 5.0, y: 6.0 },
            vel: Vel { dx: 7.0, dy: 8.0 },
        });

        let mut count = 0;
        for ptrs in world.query_table_raw::<Transform>() {
            unsafe {
                let pos = &*(ptrs[0] as *const Pos);
                assert!(pos.x == 1.0 || pos.x == 5.0);
            }
            count += 1;
        }
        assert_eq!(count, 2);
    }

    // --- Typed query_table tests ---

    #[test]
    fn typed_query_table_ref() {
        let mut world = crate::world::World::new();
        world.spawn(Transform {
            pos: Pos { x: 1.0, y: 2.0 },
            vel: Vel { dx: 3.0, dy: 4.0 },
        });

        for row in world.query_table::<Transform>() {
            assert_eq!(row.pos.x, 1.0);
            assert_eq!(row.vel.dx, 3.0);
        }
    }

    #[test]
    fn typed_query_table_mut() {
        let mut world = crate::world::World::new();
        let e = world.spawn(Transform {
            pos: Pos { x: 1.0, y: 2.0 },
            vel: Vel { dx: 3.0, dy: 4.0 },
        });

        for row in world.query_table_mut::<Transform>() {
            row.pos.x += 10.0;
        }

        assert_eq!(world.get::<Pos>(e), Some(&Pos { x: 11.0, y: 2.0 }));
    }

    #[test]
    fn typed_query_table_manual_impl() {
        let mut world = crate::world::World::new();
        world.spawn(PosVel {
            pos: Pos { x: 7.0, y: 8.0 },
            vel: Vel { dx: 9.0, dy: 10.0 },
        });

        for row in world.query_table::<PosVel>() {
            assert_eq!(row.pos.x, 7.0);
            assert_eq!(row.vel.dx, 9.0);
        }
    }

    #[test]
    fn typed_query_table_mut_manual() {
        let mut world = crate::world::World::new();
        let e = world.spawn(PosVel {
            pos: Pos { x: 1.0, y: 2.0 },
            vel: Vel { dx: 3.0, dy: 4.0 },
        });

        for row in world.query_table_mut::<PosVel>() {
            row.pos.x += 100.0;
        }

        assert_eq!(world.get::<Pos>(e), Some(&Pos { x: 101.0, y: 2.0 }));
    }

    // --- Edge cases ---

    #[test]
    fn typed_query_table_empty() {
        let mut world = crate::world::World::new();
        assert_eq!(world.query_table::<Transform>().count(), 0);
        assert_eq!(world.query_table_mut::<Transform>().count(), 0);
    }

    #[test]
    fn multiple_table_types_coexist() {
        #[derive(Clone, Copy, Debug, PartialEq, minkowski_derive::Table)]
        struct JustPos {
            pos: Pos,
        }

        let mut world = crate::world::World::new();
        world.spawn(Transform {
            pos: Pos { x: 1.0, y: 0.0 },
            vel: Vel { dx: 0.0, dy: 0.0 },
        });
        world.spawn(JustPos {
            pos: Pos { x: 2.0, y: 0.0 },
        });

        // Each table query only sees its own archetype
        assert_eq!(world.query_table::<Transform>().count(), 1);
        assert_eq!(world.query_table::<JustPos>().count(), 1);

        // Dynamic query sees both (both have Pos)
        assert_eq!(world.query::<&Pos>().count(), 2);
    }

    #[test]
    fn query_table_many_rows() {
        let mut world = crate::world::World::new();
        for i in 0..1000 {
            world.spawn(Transform {
                pos: Pos {
                    x: i as f32,
                    y: 0.0,
                },
                vel: Vel { dx: 1.0, dy: 0.0 },
            });
        }

        let sum: f32 = world.query_table::<Transform>().map(|row| row.pos.x).sum();
        // Sum of 0..1000 = 999*1000/2 = 499500
        assert_eq!(sum, 499500.0);
    }

    #[test]
    fn query_table_size_hint() {
        let mut world = crate::world::World::new();
        for _ in 0..5 {
            world.spawn(Transform {
                pos: Pos { x: 0.0, y: 0.0 },
                vel: Vel { dx: 0.0, dy: 0.0 },
            });
        }

        let iter = world.query_table::<Transform>();
        assert_eq!(iter.size_hint(), (5, Some(5)));
    }
}
